version: '3.7'
services:
  backend:
    image: star-wars-api:1.0.0
    build: .
    container_name: star-wars-api
    ports:
      - "8080:8080"
    networks:
      - default
    environment:
      - MONGO_URI=star-wars-api-mongo
      - MONGO_PORT=27017
      - APP_PROFILE=cloud
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6
    container_name: star-wars-api-mongo
    ports:
      - "27017:27017"