server:
  servlet:
    context-path: /star-wars/api

spring:
  profiles:
    active: localhost

swapi:
  api:
    uri: swapi.co/api

build:
  version: @project.version@
  date: @timestamp@

---

spring:
  profiles: localhost
  data:
    mongodb:
      host: localhost
      port: 27017
      database: star-wars

---

spring:
  profiles: cloud
  data:
    mongodb:
      host: ${MONGO_URI}
      port: ${MONGO_PORT}
      database: star-wars
